---
name: Build

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build
        uses: ConsenSys/github-actions/docs-build@7256f3d39c7bb71ec4ca9fc6078991302d4c8650 # main