---
name: Build

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build
        uses: ConsenSys/github-actions/docs-build@31dbb917dd78b1dc18b4838a2d7d598b359b834f # main
