---
name: Check file name case

on:
  pull_request:
    branches:
      - main

jobs:
  case:
    name: Check for case being inconsistent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["docs"]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Case check action
        uses: ConsenSys/github-actions/docs-case-check@31dbb917dd78b1dc18b4838a2d7d598b359b834f # main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOC_DIR: ${{ matrix.folder }}
          SKIP_TEST: true
