---
name: Check for broken links

on:
  pull_request:
    branches:
      - main

jobs:

  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: LinkCheck
        uses: ConsenSys/github-actions/docs-link-check@7256f3d39c7bb71ec4ca9fc6078991302d4c8650 # main
        with:
          CONFIG_FILE: .linkspector.yml
