---
name: Trivy

on:
  pull_request:
    branches:
      - main

jobs:
  trivy:
    name: Run trivy scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Trivy
        uses: ConsenSys/github-actions/trivy@7256f3d39c7bb71ec4ca9fc6078991302d4c8650 # main
        