---
name: trivy-cache-db

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"      

jobs:
  trivy:
    name: Run trivy scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Trivy Cache
        uses: ConsenSys/github-actions/trivy-update-cache@31dbb917dd78b1dc18b4838a2d7d598b359b834f # main
